name: Zyten's Blog
description: Ordinary(?) Blog
meta_description: "Zyten's Blog, Ordinary(?) Blog"

aboutPage: true

markdown: redcarpet
#highlighter: pygments #Requires Python 2.7
highlighter: rouge

gems: [jekyll-paginate]

paginate: 20
baseurl: /
domain_name: 'http://sruban.me'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'zyten'

# Details for the RSS feed generator
url:            'http://sruban.me'
author:         'Ruban Selvarajah'
authorTwitter:  'zyten'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
